language: objective-c
osx_image: xcode10
before_install:
  - gem install xcpretty -N
  - pod install
script:
  - xctool -workspace PriceScanner.xcworkspace -scheme PriceScanner -sdk iphonesimulator | xcpretty